### ISSUE TITLE
Unable to get current languages.

### ISSUE THREAD

**Issue by KylerOlsen** [samuelbradshaw/python-scripture-scraper#2]
The current languages can no longer be scraped from `https://www.churchofjesuschrist.org/languages?lang=eng`.

```
Getting languages
Found 0 languages


Creating metadata-languages.json
Creating metadata-scriptures.json
Creating metadata-uri-to-name.json

Traceback (most recent call last):
  File "d:\...\python-scripture-scraper\scrape.py", line 1265, in <module>
    main()
  File "d:\...\python-scripture-scraper\scrape.py", line 132, in main
    output_full_content(config.DEFAULT_LANG)
  File "d:\...\python-scripture-scraper\scrape.py", line 727, in output_full_content
    if metadata_scriptures['languages'][bcp47_lang]['churchAvailability'][publication_slug]:
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'en'
```

**Comment by KylerOlsen** [comment]
The best [work around](https://github.com/KylerOlsen/python-scripture-scraper/commit/2cba249a629628faa03f9610924ab46ab817b186) I found so far is it use an older version of the page using the Wayback Machine.

**Comment by samuelbradshaw** [comment]
Thanks for your report! Glad you found a workaround. I'll see if I can find a longer-term fix later after work today.

**Comment by samuelbradshaw** [comment]
Fixed in this commit: https://github.com/samuelbradshaw/python-scripture-scraper/commit/ea2fb14f8522adf4f15e044c125ce4698b77915f
